export const UserData = [
  {
    Name: 'Steven Bartlett',
    Email: 'Nash.Reilly@yahoo.com',
    Password: 'ANtOngcyWNV2yDE',
    Voted: true,
    img:'/public/assets/img/CEO.JPG',
    id: '1',
  },
  {
    Name: 'Howard Stern',
    Email: 'Edd26@gmail.com',
    Password: 'jcycAQ9aptD_dtw',
    Voted: true,
    img:'/public/assets/img/Howard-Stern.jpg',
    id: '2',
  },
  {
    Name: 'Joe-Rogen',
    Email: 'Alena.Mraz@yahoo.com',
    Password: 'clqsmts2r9kdlL6',
    Voted: true,
    img:'/public/assets/img/Joe-Rogen.jpeg'
    id: '3',
  },
  {
    Name: 'Jay Shetty',
    Email: 'Jess71@hotmail.com',
    Password: 'lVJNzzaW2PUrTsv',
    Voted: true,
    img:'/public/assets/img/jay-shetty.jpg'
    id: '4',
  },
  {
    Name: 'Miss Angelina Maggio',
    Email: 'Tiffany_West@hotmail.com',
    Password: 'a6tlmghYgIucvH7',
    Voted: false,
    id: '5',
  },
  {
    Name: 'Darla Conroy',
    Email: 'Delbert.Homenick98@yahoo.com',
    Password: 'tu8sw4A0O9XDnFu',
    Voted: false,
    id: '6',
  },
  {
    Name: 'Rick Langworth',
    Email: 'Pierce67@gmail.com',
    Password: 'wFoL7PiCPfY35Ju',
    Voted: false,
    id: '7',
  },
  {
    Name: 'Yvonne Ebert',
    Email: 'Keely92@hotmail.com',
    Password: 'n22xb5HO2YXlV4d',
    Voted: true,
    id: '8',
  },
  {
    Name: 'Celia Hettinger',
    Email: 'Keshawn_Upton42@yahoo.com',
    Password: 'eDfOQBUjFtH2Hkk',
    Voted: false,
    id: '9',
  },
  {
    Name: 'Rick Von',
    Email: 'Esmeralda_Crooks@yahoo.com',
    Password: 'KTnI2Upu0kN9Mwi',
    Voted: false,
    id: '10',
  },
  {
    Name: 'Geneva Crona',
    Email: 'Russel40@hotmail.com',
    Password: 'SDbDcZwjVqdBD0q',
    Voted: false,
    id: '11',
  },
  {
    Name: 'Lonnie Jerde',
    Email: 'Nannie_Gleason@hotmail.com',
    Password: '_Arf6KKet6n10pD',
    Voted: false,
    id: '12',
  },
  {
    Name: 'Amos Cremin',
    Email: 'Billy.Hilll27@gmail.com',
    Password: 'PFr2Cc6SgiQwK1a',
    Voted: true,
    id: '13',
  },
  {
    Name: 'Jo Hahn',
    Email: 'Lina.Daugherty@hotmail.com',
    Password: 'riD5YMjGtaPhE9V',
    Voted: false,
    id: '14',
  },
  {
    Name: 'Maurice Abshire',
    Email: 'Tristin.Mraz53@hotmail.com',
    Password: 'uSfORXBImriSpn0',
    Voted: false,
    id: '15',
  },
  {
    Name: 'Raul Greenfelder',
    Email: 'Richmond.Schiller92@gmail.com',
    Password: 'xTYIVuxDltoAWs0',
    Voted: false,
    id: '16',
  },
  {
    Name: 'Kate Ritchie',
    Email: 'Patsy_Williamson58@gmail.com',
    Password: 'WX6JOAYdj3WYHnB',
    Voted: false,
    id: '17',
  },
  {
    Name: 'Blake Lueilwitz Jr.',
    Email: 'Maryjane30@hotmail.com',
    Password: 'w_QOMjx53cwFs8O',
    Voted: false,
    id: '18',
  },
  {
    Name: 'Johnnie Mitchell',
    Email: 'Dimitri53@hotmail.com',
    Password: 'bT1XmTO1cLZlBTT',
    Voted: false,
    id: '19',
  },
  {
    Name: 'Harold Satterfield',
    Email: 'Robin39@hotmail.com',
    Password: 'Vw8edGyuFQ9ffsH',
    Voted: true,
    id: '20',
  },
  {
    Name: 'Loren McGlynn',
    Email: 'Kiara.Kerluke68@gmail.com',
    Password: '1BgR8hSy3l4EEW1',
    Voted: true,
    id: '21',
  },
  {
    Name: 'Danny Welch',
    Email: 'Margarett6@gmail.com',
    Password: 'OHFpaZ5jLd8KSXh',
    Voted: false,
    id: '22',
  },
  {
    Name: 'Javier Roberts',
    Email: 'Olen.Weimann@gmail.com',
    Password: 'yy4KUxt64PQks5t',
    Voted: true,
    id: '23',
  },
  {
    Name: 'Tasha Heidenreich',
    Email: 'Golda_Ortiz@hotmail.com',
    Password: 'mw6rX3aOivyUS6j',
    Voted: false,
    id: '24',
  },
  {
    Name: 'Doreen Hane',
    Email: 'Heaven.Dickinson78@hotmail.com',
    Password: '_QUb9A0r0af_t19',
    Voted: false,
    id: '25',
  },
  {
    Name: 'Gail Grimes',
    Email: 'Brooks37@hotmail.com',
    Password: 'dByu32DCVwX7N0c',
    Voted: true,
    id: '26',
  },
  {
    Name: 'Melanie Nitzsche',
    Email: 'Mikayla.King@yahoo.com',
    Password: 'k84hyu2BIYElcaB',
    Voted: true,
    id: '27',
  },
  {
    Name: 'Tina Konopelski',
    Email: 'Keegan_Cummerata@gmail.com',
    Password: '2E3b1j7Yjf3ii2E',
    Voted: true,
    id: '28',
  },
  {
    Name: 'Lauren Erdman',
    Email: 'Lourdes53@gmail.com',
    Password: '37xZde4hpKq6Y4y',
    Voted: true,
    id: '29',
  },
  {
    Name: 'Frances Batz',
    Email: 'Willis24@hotmail.com',
    Password: '6OFBtT8VYNiLTlI',
    Voted: false,
    id: '30',
  },
  {
    Name: 'Terri Friesen',
    Email: 'Bobby.Turcotte33@yahoo.com',
    Password: 'XHLaNnYbAvkKvnq',
    Voted: true,
    id: '31',
  },
  {
    Name: 'Meghan Romaguera',
    Email: 'Kaitlin8@yahoo.com',
    Password: 'iiJRCMRs2FqiXaW',
    Voted: false,
    id: '32',
  },
  {
    Name: 'Ms. Julian Pouros',
    Email: 'Nolan_Kozey@yahoo.com',
    Password: 'NHIXbc4_H7SsXiB',
    Voted: true,
    id: '33',
  },
  {
    Name: 'Justin Boehm',
    Email: 'Rosie88@gmail.com',
    Password: 'RZqnIfxnXph5s04',
    Voted: false,
    id: '34',
  },
  {
    Name: 'Tyrone Heathcote',
    Email: 'Finn.Welch@yahoo.com',
    Password: 'CEznAzJ8Jso2l_T',
    Voted: true,
    id: '35',
  },
  {
    Name: 'Jeannette Balistreri',
    Email: 'Angelita_Ondricka62@yahoo.com',
    Password: '6G6HPhdxhvMnxWp',
    Voted: true,
    id: '36',
  },
  {
    Name: 'Francis Gleason',
    Email: 'Sabrina80@gmail.com',
    Password: 'KlnWMoGjDTQFP2t',
    Voted: false,
    id: '37',
  },
  {
    Name: 'Gretchen Osinski',
    Email: 'Velma_Pfannerstill13@hotmail.com',
    Password: 'Hib2jjd36t1I25A',
    Voted: true,
    id: '38',
  },
  {
    Name: 'Stanley Hoppe',
    Email: 'Sven.Pagac@hotmail.com',
    Password: 'XZda7NfeY275BTA',
    Voted: true,
    id: '39',
  },
  {
    Name: 'Mrs. Dixie Hand',
    Email: 'Leila.Schowalter@gmail.com',
    Password: 'fXanauI_ocguT5r',
    Voted: true,
    id: '40',
  },
  {
    Name: 'Dolores Rosenbaum',
    Email: 'Nigel.Renner@yahoo.com',
    Password: '9DTBuM0fRUFykE1',
    Voted: false,
    id: '41',
  },
  {
    Name: 'Rolando Parker',
    Email: 'Joy.Cormier@yahoo.com',
    Password: 'soK8WXZfOqaTl0i',
    Voted: false,
    id: '42',
  },
  {
    Name: 'Dianna Dickinson',
    Email: 'Emma85@hotmail.com',
    Password: '4xlAzT4gg35mtfR',
    Voted: false,
    id: '43',
  },
  {
    Name: 'Georgia Considine',
    Email: 'Orie.Murazik@gmail.com',
    Password: 'xIf60xIlVzLScw5',
    Voted: true,
    id: '44',
  },
  {
    Name: 'Caroline Miller',
    Email: 'Janiya31@yahoo.com',
    Password: 'UeRwXTuAw_HDcSW',
    Voted: true,
    id: '45',
  },
  {
    Name: 'Mr. Sabrina Wehner',
    Email: 'Kyleigh_Torphy@hotmail.com',
    Password: 'DmBjQYHwYn_UV9n',
    Voted: true,
    id: '46',
  },
  {
    Name: 'Courtney Batz',
    Email: 'Sophia.Nader48@gmail.com',
    Password: 'M7ETzEfie7iq243',
    Voted: false,
    id: '47',
  },
  {
    Name: 'Kendra Feil',
    Email: 'Danny27@gmail.com',
    Password: 'UG9xy0BsBh0heg_',
    Voted: true,
    id: '48',
  },
  {
    Name: 'Percy Heathcote V',
    Email: 'Blanche71@yahoo.com',
    Password: 'v_YcYA_G42ImJad',
    Voted: false,
    id: '49',
  },
  {
    Name: 'Deborah Satterfield',
    Email: 'Sanford.Heidenreich@hotmail.com',
    Password: 'cTOooiFq9blZIXB',
    Voted: false,
    id: '50',
  },
  {
    Name: 'Joey Stoltenberg',
    Email: 'Delaney17@gmail.com',
    Password: 'uK8HP0241AiJOCM',
    Voted: false,
    id: '51',
  },
  {
    Name: 'Lynda MacGyver',
    Email: 'Eden41@yahoo.com',
    Password: 'ef0jedr84XObaAv',
    Voted: false,
    id: '52',
  },
  {
    Name: 'Tiffany Gutmann MD',
    Email: 'Sheldon_Greenfelder@hotmail.com',
    Password: 'kEq1xvR1qktctom',
    Voted: false,
    id: '53',
  },
  {
    Name: 'Adam Reynolds',
    Email: 'Ryley_Altenwerth@yahoo.com',
    Password: 'Catenq7thjvf4TS',
    Voted: false,
    id: '54',
  },
  {
    Name: 'Dr. Nina Weimann',
    Email: 'Dianna.McGlynn14@yahoo.com',
    Password: 'J5o6EHiWfruU63T',
    Voted: true,
    id: '55',
  },
  {
    Name: 'Kelvin Schneider',
    Email: 'Haskell_Dickens@yahoo.com',
    Password: '4d_avRdR2IouI41',
    Voted: true,
    id: '56',
  },
  {
    Name: 'Francis Baumbach',
    Email: 'Johnnie.Bauch@gmail.com',
    Password: '4A_E_0_oMcB4Wsr',
    Voted: false,
    id: '57',
  },
  {
    Name: 'Donald Halvorson',
    Email: 'Teagan64@hotmail.com',
    Password: 'niydF_oc1V1PzEb',
    Voted: false,
    id: '58',
  },
  {
    Name: 'Tabitha Grant',
    Email: 'Emanuel48@hotmail.com',
    Password: 'hVCR_jIsZG2lHr3',
    Voted: false,
    id: '59',
  },
  {
    Name: 'Denise Simonis',
    Email: 'Hanna.Koepp@hotmail.com',
    Password: 'o5rSymjbUWMFEUP',
    Voted: true,
    id: '60',
  },
  {
    Name: 'Debbie Harvey',
    Email: 'Charlotte.Kautzer20@hotmail.com',
    Password: 'pj4coI_KbkMIhHE',
    Voted: true,
    id: '61',
  },
  {
    Name: 'Gwen Jenkins',
    Email: 'Arnold_Gulgowski75@yahoo.com',
    Password: 'TJ1mAOS4_FHsBe0',
    Voted: true,
    id: '62',
  },
  {
    Name: 'Bill Hirthe',
    Email: 'Kellen21@yahoo.com',
    Password: 'MgkzwZlGTVOgr7P',
    Voted: false,
    id: '63',
  },
  {
    Name: 'Dustin Green',
    Email: 'Marcelina.Mertz57@yahoo.com',
    Password: 'SOkY4kT86QwkomW',
    Voted: true,
    id: '64',
  },
  {
    Name: 'Kendra Windler',
    Email: 'Jeff_Rodriguez89@gmail.com',
    Password: 'CG9KCqLgVo5KU2m',
    Voted: false,
    id: '65',
  },
  {
    Name: 'Miss Derrick Schuster',
    Email: 'Drew.Kub23@hotmail.com',
    Password: 'PZkF5_LC_VK_G6X',
    Voted: false,
    id: '66',
  },
  {
    Name: 'Philip Nicolas',
    Email: 'Jackson_Bailey53@gmail.com',
    Password: 'MwrQsroLETKNCxN',
    Voted: false,
    id: '67',
  },
  {
    Name: 'Harry Fay',
    Email: 'Gabrielle80@hotmail.com',
    Password: 'kk2u0mrMPsCYcWM',
    Voted: false,
    id: '68',
  },
  {
    Name: 'Maria Wilderman',
    Email: 'Emery_Parisian@yahoo.com',
    Password: 'WTndeWf2m5wDz5F',
    Voted: false,
    id: '69',
  },
  {
    Name: 'Larry Pfannerstill',
    Email: 'Etha.Bruen16@gmail.com',
    Password: 'YEltTJt45FUv4rZ',
    Voted: false,
    id: '70',
  },
  {
    Name: 'Luis Brekke',
    Email: 'Chester43@gmail.com',
    Password: 'OLDsIt2Aahar_7g',
    Voted: true,
    id: '71',
  },
  {
    Name: 'Leon Welch',
    Email: 'Roselyn.Anderson67@hotmail.com',
    Password: 'g0hcs5vhWvG09YB',
    Voted: false,
    id: '72',
  },
  {
    Name: 'Jared Bauch',
    Email: 'Andres.Stehr@yahoo.com',
    Password: '0se_QUO05fPI7zp',
    Voted: true,
    id: '73',
  },
  {
    Name: 'Ms. Grant McClure',
    Email: 'Gilda_Daniel11@yahoo.com',
    Password: '6KuEsIjOKMqrRP4',
    Voted: false,
    id: '74',
  },
  {
    Name: 'Jessica Bashirian',
    Email: 'Eden_Graham@hotmail.com',
    Password: 'rV6oP8etjtN3k7x',
    Voted: true,
    id: '75',
  },
  {
    Name: 'Lucy Stracke I',
    Email: 'Clyde_Waelchi@hotmail.com',
    Password: 'dO_rwW56UJNoPiQ',
    Voted: true,
    id: '76',
  },
  {
    Name: 'Kerry Conroy',
    Email: 'Darien50@hotmail.com',
    Password: '0sk3XDzABRGaQy4',
    Voted: true,
    id: '77',
  },
  {
    Name: 'Silvia Ritchie',
    Email: 'Kenny_Windler60@hotmail.com',
    Password: 'N9b6wtC8cg4I21v',
    Voted: false,
    id: '78',
  },
  {
    Name: 'Viola Stanton',
    Email: 'Kevin.Mayert@gmail.com',
    Password: 'LU_M0ajIIVgbaZs',
    Voted: true,
    id: '79',
  },
  {
    Name: 'Javier Zieme',
    Email: 'Bertha.Robel95@yahoo.com',
    Password: 'xX3vX4Ay8FgkWmY',
    Voted: true,
    id: '80',
  },
  {
    Name: 'Karl Schumm',
    Email: 'Triston_Feeney@yahoo.com',
    Password: 'rW8tLE9vsEaVqu0',
    Voted: true,
    id: '81',
  },
  {
    Name: 'Miss Betsy Auer',
    Email: 'Carter_Abernathy52@hotmail.com',
    Password: 'jF5G9SKFVDg4JQ_',
    Voted: false,
    id: '82',
  },
  {
    Name: 'Dana Barton',
    Email: 'Candace_Wilkinson73@yahoo.com',
    Password: 'FzFHhAOnOthiqmT',
    Voted: false,
    id: '83',
  },
  {
    Name: 'Julio Reichert',
    Email: 'Carmella96@gmail.com',
    Password: '5gqtT185Cze2GRD',
    Voted: false,
    id: '84',
  },
  {
    Name: 'Delia Vandervort DDS',
    Email: 'Skyla11@gmail.com',
    Password: 'oVM6hri2orAaadf',
    Voted: false,
    id: '85',
  },
  {
    Name: 'Miss Darin Fritsch',
    Email: 'Beryl28@hotmail.com',
    Password: 'ZeD7puQ1pkWwwIs',
    Voted: false,
    id: '86',
  },
  {
    Name: 'Wilma Kunde',
    Email: 'Wilhelmine_Christiansen@hotmail.com',
    Password: 'S3A2pWTm4u3b6Sr',
    Voted: false,
    id: '87',
  },
  {
    Name: 'Lonnie Hamill',
    Email: 'Stella.Hintz@yahoo.com',
    Password: 'j_JDGwNywWJ3jP_',
    Voted: true,
    id: '88',
  },
  {
    Name: 'Don Labadie MD',
    Email: 'Mable28@yahoo.com',
    Password: 'RS2YoQQak4WR8fj',
    Voted: false,
    id: '89',
  },
  {
    Name: 'Travis Tremblay',
    Email: 'Kaelyn_Fahey@hotmail.com',
    Password: 'TS1vMf3kgyWInHq',
    Voted: true,
    id: '90',
  },
  {
    Name: 'Ed Jones',
    Email: 'Napoleon.Corwin60@gmail.com',
    Password: 'konYC6sfAU1bBsC',
    Voted: true,
    id: '91',
  },
  {
    Name: 'Krystal Reichert',
    Email: 'Murphy.Towne@yahoo.com',
    Password: 'BkCW6RR7cIH8tVF',
    Voted: true,
    id: '92',
  },
  {
    Name: 'Stewart Blick',
    Email: 'Jennifer91@gmail.com',
    Password: 'PDDufMiPDthsYjI',
    Voted: true,
    id: '93',
  },
  {
    Name: 'Christie Strosin',
    Email: 'Rhoda13@gmail.com',
    Password: 'Z9mA09x_lvRf4iS',
    Voted: false,
    id: '94',
  },
  {
    Name: 'Christy Smith',
    Email: 'Leopoldo_Turcotte@yahoo.com',
    Password: 'mO38x2XdCO6197s',
    Voted: true,
    id: '95',
  },
  {
    Name: 'Eloise Koelpin',
    Email: 'Tiara34@yahoo.com',
    Password: 'vbzOh7RJjNB3X5W',
    Voted: false,
    id: '96',
  },
  {
    Name: 'Sophia Johnston',
    Email: 'Harrison_Howell@yahoo.com',
    Password: '6Y67hRjYzoDD0c9',
    Voted: false,
    id: '97',
  },
  {
    Name: 'Micheal Haley',
    Email: 'Lela.Witting91@hotmail.com',
    Password: '3f9TrZ73ZBvWnBt',
    Voted: true,
    id: '98',
  },
  {
    Name: 'Olive Osinski',
    Email: 'Gabrielle_Franecki52@yahoo.com',
    Password: 'Lz2Znmayt20JtqB',
    Voted: true,
    id: '99',
  },
  {
    Name: 'Mandy DuBuque',
    Email: 'Ervin_Aufderhar@gmail.com',
    Password: '5k7qYiPPrGn2Ei0',
    Voted: false,
    id: '100',
  },
]
